export const LAB_METRIC_HELP = {
  backlog: "Requested simulation tick minus current worker tick; values above 0 mean catch-up work remains.",
  lifetimeHit: "Agent wins / resolved trades across its full lifetime.",
  lifetimeAveragePayoff: "Agent total payoff / resolved trades across its full lifetime.",
  recentAveragePayoff: "Average of this agent's last Agent payoff window resolved payoffs; default window is 12 payoffs, not ticks.",
  rollingHit: "Positive payoffs / count over this agent's last Agent payoff window resolved payoffs; default is 12 payoffs, not ticks.",
  rollingAveragePayoff: "Mean payoff over this agent's last Agent payoff window resolved payoffs; default is 12 payoffs.",
  rollingLoss: "Mean max(0, -payoff) over this agent's last Agent payoff window resolved payoffs; default is 12 payoffs.",
  clusterHit: "Wins / resolved trades for agents in the latest strategy-map cluster sample, refreshed about every 250 ticks.",
  clusterAveragePayoff: "Resolved payoff / resolved trades for agents in the latest strategy-map cluster sample.",
  clusterDistance: "Distance from the cluster center in normalized strategy-feature space.",
  clusterPercentile: "This agent's cluster-distance percentile; 0 is central, 1 is farthest in its cluster.",
  averagePerceptionLag: "Mean tick lag across this agent's active perception windows.",
  longestPerceptionWindow: "Longest active perception or scale window in this agent's genome, in ticks.",
  pendingDensityScale: "Pending-trade count is divided by this tick-scale value for the pending-density input.",
  topologyMutation: "Mean of add/disable/reenable unit and connection mutation rates.",
  weightMutation: "Weight mutation rate x weight mutation standard deviation.",
  biasMutation: "Mean gate/output bias mutation rate x standard deviation.",
  perceptionMutation: "Probability that perception/payoff-scale timing traits mutate on birth.",
  profileDrift: "Mutation standard deviation applied to this agent's own mutation-rate profile.",
  learnedDeltaNorm: "sqrt(sum(delta^2)) over learned connection, gate-bias, and output-bias deltas.",
  recentLearning: "Last learning signal stored after payoff or reproduction feedback; payoff signals use tanh(payoff) and clamp to [-1, 1].",
  learningUpdates: "Count of feedback events that actually changed learned deltas.",
  reproductionLearning: "Count of reproduction-feedback events that actually changed learned deltas.",
  learningRate: "Mean of this agent's weight and bias learning rates.",
  learningDecay: "Per-step decay applied to learned deltas: next delta = delta x (1 - decay).",
  maxLearnedDelta: "Absolute cap for each learned delta after learning and clamping.",
  plasticityDrift: "Mutation standard deviation for learning-rate, reward, decay, and max-delta traits.",
} as const;

export const RUN_DIAGNOSTIC_HELP = {
  cumulativePayoff: "Running sum of resolved trade payoffs; this is payoff units, not portfolio percent.",
  payoffDrawdown: "Cumulative payoff minus its highest prior cumulative payoff; negative values are drawdowns.",
  populationDrawdown: "Population minus its highest prior population; negative values show drop from peak.",
  deathCauses: "Deaths per run bucket: energy below threshold, health below threshold, or both at death.",
  bucketHitRate: "Wins / resolved trades in each selected-range bucket; the range is split into 20 tick buckets.",
  bucketAveragePayoff: "Bucket total payoff / resolved trades in that bucket.",
  bucketDownsideVolatility: "sqrt(mean(max(0, -bucketTotalPayoff)^2)) across the selected range's 20 buckets.",
  bucketVaR5: "5% lower-tail quantile of bucket total payoffs; more negative means worse bucket risk.",
  bucketCVaR5: "Mean bucket total payoff at or below Bucket VaR 5%.",
  bucketVaR1: "1% lower-tail quantile of bucket total payoffs; more negative means worse tail risk.",
  bucketCVaR1: "Mean bucket total payoff at or below Bucket VaR 1%.",
  sharpe: "For each agent: lifetime average trade payoff / sample standard deviation of its trade payoffs.",
  sortino: "For each agent: lifetime average trade payoff / downside deviation of its trade payoffs.",
  downsideVolatility: "sqrt(mean(max(0, -tradePayoff)^2)); larger values mean larger downside moves.",
  tradeVaR5: "5% lower-tail quantile of individual trade payoffs; more negative means worse trade risk.",
  tradeCVaR5: "Mean individual trade payoff at or below Trade VaR 5%.",
  tradeVaR1: "1% lower-tail quantile of individual trade payoffs; more negative means worse tail risk.",
  tradeCVaR1: "Mean individual trade payoff at or below Trade VaR 1%.",
  payoffDistribution: "Histogram of individual resolved trade payoffs.",
  longShortBreakdown: "For each direction: trades, wins / trades, and total payoff / trades.",
  horizonBreakdown: "For each horizon bucket: trades, wins / trades, and total payoff / trades.",
  strengthBreakdown: "For each strength bucket: trades, wins / trades, and total payoff / trades.",
  agentAge: "Age exposure inside the selected tick range: min(death tick, range end) - max(birth tick, range start).",
  topLineagePayoffShare: "abs(payoff of highest signed-payoff lineage) / sum(abs(lineage payoff)).",
} as const;
