import type { SpawnerConfig } from "./spawnerSimulation";

const SPAWNER_CONTROL_HELP: Partial<Record<keyof SpawnerConfig, string>> = {
  initialSpawners: "How many food-spawner agents start a new world. More agents means more competing entry ideas from tick one.",
  maxSpawners: "Hard cap on living spawner agents. Reproduction stops at this cap, and new worlds start no higher than it.",
  deathEnergy: "Agents below this energy are removed. Higher values make starvation happen sooner.",
  deathHealth: "Agents at or below this health are removed. Higher values make bad trades more lethal.",
  initialEnergyMin: "Lowest starting energy for new founder agents.",
  initialEnergyMax: "Highest starting energy for new founder agents.",
  initialHealth: "Starting health, and the current healing cap, for spawner agents.",
  initialCooldownMaxTicks: "Maximum random starting wait, in ticks, before a founder can spawn its first opportunity.",
  defaultSpawnThreshold: "Founder default for the inherited long/short score cutoff required before an agent creates an opportunity marker.",
  spawnCost: "Base energy paid whenever an agent creates an opportunity.",
  minimumSpawnEnergySurplus: "Extra energy above spawn cost required before an agent is allowed to act.",
  defaultMinSignalStrength: "Founder default for the inherited lower bound on opportunity strength. Children can mutate this independently.",
  defaultDeltaLag1FromTicks: "Founder default for the first ROC-delta sample start. Children can mutate this lag independently.",
  defaultDeltaLag1ToTicks: "Founder default for the first ROC-delta sample end. Children can mutate this lag independently.",
  defaultDeltaLag2FromTicks: "Founder default for the second ROC-delta sample start. Children can mutate this lag independently.",
  defaultDeltaLag2ToTicks: "Founder default for the second ROC-delta sample end. Children can mutate this lag independently.",
  defaultDeltaLag3FromTicks: "Founder default for the third ROC-delta sample start. Children can mutate this lag independently.",
  defaultDeltaLag3ToTicks: "Founder default for the third ROC-delta sample end. Children can mutate this lag independently.",
  defaultDeltaLag4FromTicks: "Founder default for the fourth ROC-delta sample start. Children can mutate this lag independently.",
  defaultDeltaLag4ToTicks: "Founder default for the fourth ROC-delta sample end. Children can mutate this lag independently.",
  defaultDeltaLag5FromTicks: "Founder default for the fifth ROC-delta sample start. This is the extra long-range perception input.",
  defaultDeltaLag5ToTicks: "Founder default for the fifth ROC-delta sample end. This is the extra long-range perception input.",
  defaultRollingWindowTicks: "Founder default window for relative mean and volatility inputs.",
  defaultLocalScaleWindowTicks: "Founder default window used to normalize ROC into local, relative units.",
  defaultLocalScaleSampleStepTicks: "Founder default spacing, in ticks, between samples used for local scale, trend, and cycle estimates.",
  defaultVolumeScaleWindowTicks: "Founder default window used to normalize candle volume into local, relative units.",
  defaultVolumeScaleSampleStepTicks: "Founder default spacing, in ticks, between samples used for local volume scale estimates.",
  defaultVolumeDeltaLagTicks: "Founder default lag for comparing current volume to recent past volume.",
  defaultVolumeAccelerationLagTicks: "Founder default lag for comparing recent volume change to the previous volume change.",
  defaultRsiWindowTicks: "Founder default window for the bounded RSI input.",
  defaultVolumePriceAgreementLagTicks: "Founder default lag for measuring whether volume confirms the current signal move.",
  defaultTrendWindowTicks: "Founder default window for the relative trend input.",
  defaultCycleWindowTicks: "Founder default window for the turning-rate cycle input.",
  defaultRoughnessSensitivity: "Founder default threshold for deciding whether small wiggles count as roughness.",
  defaultPendingDensityScale: "Founder default scale that turns unresolved opportunity count into the pending-density input.",
  founderPerceptionRandomizationTicks: "How broadly founder agents are randomized around the perception defaults at world creation.",
  energyDrainPerTick: "Base energy drain per tick. This is Toy Market upkeep, separate from Ant World's energy model.",
  foodHistoryTicks: "How many ticks resolved opportunity markers remain visible on the chart.",
  transactionCost: "Raw ROC/signal cost per full-strength opportunity, subtracted before payoff-scale normalization.",
  defaultPayoffScaleWindowTicks: "Founder default window used to normalize resolved opportunity payoff into local signal units.",
  defaultPayoffScaleSampleStepTicks: "Founder default spacing, in ticks, between samples used for payoff-scale normalization.",
  rewardScale: "Multiplier converting positive payoff into agent energy.",
  lossHealthScale: "Multiplier converting negative payoff into health damage.",
  healthGainScale: "Multiplier converting positive payoff into health recovery.",
  recentResolvedPayoffWindow: "Number of recent resolved opportunities used for the global rolling loss chart.",
  agentRecentPayoffWindow: "Number of recent payoffs kept per agent for display and historical inspection.",
  uniquenessPopulationLimit: "Maximum living population where automatic uniqueness scoring stays on. Higher values keep the chart active for larger populations but cost more CPU.",
  plasticityWeightLearningRate: "How strongly reward feedback changes learned connection weights during an agent's lifetime.",
  plasticityBiasLearningRate: "How strongly reward feedback changes learned gate and output biases during an agent's lifetime.",
  plasticityPositiveRewardMultiplier: "Multiplier applied to profitable opportunity feedback before learning updates are bounded.",
  plasticityNegativeRewardMultiplier: "Multiplier applied to losing opportunity feedback before learning updates are bounded.",
  plasticityReproductionRewardStrength: "Positive learning signal from 0 to 1 applied when an eligible reproduce decision creates a child.",
  plasticityExperienceDecayRate: "Fraction of learned lifetime deltas that fades each tick before the next decision.",
  plasticityMaxLearnedDelta: "Safety cap on the absolute size of any one learned lifetime weight or bias delta.",
  plasticityEligibilityTraceStrength: "How much saved decision traces influence reward-modulated learning updates.",
  plasticityMutationStdDev: "How much an agent's inherited learning settings drift when it creates a child.",
  reproductionEnergy: "Minimum energy required before an agent's reproduce output can create a child.",
  reproductionCost: "Energy paid by the parent when it reproduces.",
  reproductionCostMinMultiplier: "Reproduction cost multiplier when the living population has maximum room available.",
  reproductionCostMaxMultiplier: "Reproduction cost multiplier when the living population reaches the population cap.",
  reproductionCostPressureCurve: "Exponential curve shaping how quickly reproduction cost rises as population room disappears. Zero is linear.",
  initialReproductionOutputBias: "Starting bias for founder reproduce probability. More negative values prevent immediate population explosions; descendants can still mutate this output over time.",
  initialHiddenUnitsMin: "Lowest number of active recurrent memory units founder agents can start with.",
  initialHiddenUnitsMax: "Highest number of active recurrent memory units founder agents can start with.",
  initialInputConnectionsPerUnit: "How many sparse input-to-gate links each founder memory unit starts with.",
  initialRecurrentConnectionsPerUnit: "How many previous-memory links each founder memory unit starts with.",
  initialOutputConnectionsPerOutput: "How many hidden-to-output links each founder output starts with, capped by available founder memory units.",
  newUnitInitialConnections: "How many legal links are attempted when mutation adds a new memory unit. At least one incoming and one outgoing link are required when legal.",
  addUnitRate: "Chance a child gains one new recurrent memory unit at birth.",
  disableUnitRate: "Chance a child disables one active memory unit at birth.",
  reenableUnitRate: "Chance a child re-enables one disabled memory unit at birth.",
  addConnectionRate: "Chance a child gains one new legal sparse connection at birth.",
  disableConnectionRate: "Chance a child disables one active connection at birth.",
  reenableConnectionRate: "Chance a child re-enables one disabled connection at birth.",
  newUnitExistingLayerChance: "Relative chance that a new memory unit appears in an already active layer.",
  newUnitNewLayerChance: "Relative chance that a new memory unit appears one layer deeper than the current deepest layer.",
  allowSkipConnections: "When on, lower layers may connect directly to deeper non-adjacent layers.",
  allowInputToOutputConnections: "When on, raw inputs may connect directly to outputs without hidden memory.",
  weightMutationRate: "Chance each connection weight mutates when a child is born.",
  weightMutationStdDev: "Typical size of small inherited weight changes.",
  weightReplaceRate: "Chance a mutating weight is replaced with a fresh random value instead of nudged.",
  newConnectionWeightStdDev: "Initial random weight spread for newly created sparse connections.",
  biasMutationRate: "Chance each gate or output bias mutates when a child is born.",
  biasMutationStdDev: "Typical size of inherited bias changes.",
  gateBiasStdDev: "Initial random bias spread for candidate, update, and reset gates.",
  outputBiasStdDev: "Initial random bias spread for long, short, strength, horizon, cooldown, and reproduce outputs.",
  brainEnergyCostPerActiveUnit: "Optional extra energy drain per tick for each active memory unit. Default is zero.",
  brainEnergyCostPerActiveConnection: "Optional extra energy drain per tick for each active connection. Default is zero.",
  brainEnergyCostPerActiveLayer: "Optional extra energy drain per tick for each active layer. Default is zero.",
  cooldownOutputMultiplierTicks: "Scales the NN cooldown output into ticks. Higher values make actions create longer waits.",
  thresholdBiasInitialStdDev: "Initial random spread for each agent's general tendency to spawn opportunities.",
  thresholdBiasMutationStdDev: "Mutation size for the agent's spawn tendency bias.",
  thresholdBiasMin: "Lower clamp on spawn tendency bias.",
  thresholdBiasMax: "Upper clamp on spawn tendency bias.",
  minHorizonTicksMutationStdDev: "Mutation size, in ticks, for the shortest prediction horizon.",
  maxHorizonTicksMutationStdDev: "Mutation size, in ticks, for the longest prediction horizon.",
  cooldownBaseTicksMutationStdDev: "Mutation size, in ticks, for each agent's base cooldown.",
  perceptionMutationRate: "Chance each mutable perception setting changes when a child is born.",
  perceptionLagMutationStdDev: "Typical mutation size, in ticks, for ROC-delta lag endpoints.",
  perceptionWindowMutationStdDev: "Typical mutation size, in ticks, for rolling, local-scale, volume-scale, RSI, trend, and cycle windows.",
  perceptionSensitivityMutationStdDev: "Typical mutation size for the roughness sensitivity setting.",
  perceptionDensityScaleMutationStdDev: "Typical mutation size for the pending-density scale.",
  payoffScaleMutationRate: "Chance each mutable payoff-scale setting changes when a child is born.",
  payoffScaleWindowMutationStdDev: "Typical mutation size, in ticks, for the payoff normalization window.",
  payoffScaleSampleStepMutationStdDev: "Typical mutation size, in ticks, for the payoff normalization sample step.",
  tradingPolicyMutationRate: "Chance each inherited trading-policy setting changes when a child is born.",
  spawnThresholdMutationStdDev: "Typical mutation size for the inherited spawn score cutoff.",
  minSignalStrengthMutationStdDev: "Typical mutation size for the inherited minimum opportunity strength.",
  mutationProfileMutationStdDev: "How much each agent's own mutation probabilities and mutation sizes drift in its children.",
  initialMinHorizonTicksMin: "Lower end of the founder range, in ticks, for the shortest resolution horizon.",
  initialMinHorizonTicksMax: "Upper end of the founder range, in ticks, for the shortest resolution horizon.",
  initialMaxHorizonTicksMin: "Lower end of the founder range, in ticks, for the longest resolution horizon.",
  initialMaxHorizonTicksMax: "Upper end of the founder range, in ticks, for the longest resolution horizon.",
  minHorizonTicksClampMin: "Lowest tick value mutation can assign to the shortest allowed resolution horizon.",
  minHorizonTicksClampMax: "Highest tick value mutation can assign to the shortest allowed resolution horizon.",
  maxHorizonTicksClampMin: "Lowest tick value mutation can assign to the longest allowed resolution horizon.",
  maxHorizonTicksClampMax: "Highest tick value mutation can assign to the longest allowed resolution horizon.",
  cooldownBaseTicksInitialMin: "Lower end of the founder range, in ticks, for inherited base cooldown.",
  cooldownBaseTicksInitialMax: "Upper end of the founder range, in ticks, for inherited base cooldown.",
  cooldownBaseTicksClampMin: "Lowest tick value mutation can assign to inherited base cooldown.",
  cooldownBaseTicksClampMax: "Highest tick value mutation can assign to inherited base cooldown.",
};

export function getSpawnerHelp(key: keyof SpawnerConfig): string | undefined {
  return SPAWNER_CONTROL_HELP[key];
}
