import type { SpawnerConfig } from "./spawnerSimulation";

export type SpawnerConfigBounds = {
  min: number;
  max: number;
  step: number;
  integer?: boolean;
};

export const SPAWNER_CONFIG_BOUNDS: Record<keyof SpawnerConfig, SpawnerConfigBounds> = {
  initialSpawners: { min: 1, max: 500, step: 1, integer: true },
  tickSeconds: { min: 0.01, max: 5, step: 0.01 },
  maxSpawners: { min: 1, max: 1000, step: 1, integer: true },
  foodHistorySeconds: { min: 1, max: 600, step: 1, integer: true },
  initialEnergyMin: { min: 0, max: 200, step: 0.5 },
  initialEnergyMax: { min: 0, max: 250, step: 0.5 },
  initialHealth: { min: 1, max: 300, step: 1 },
  initialCooldownMax: { min: 0, max: 10, step: 0.05 },
  spawnThreshold: { min: 0, max: 1.5, step: 0.01 },
  spawnCost: { min: 0, max: 20, step: 0.05 },
  minimumSpawnEnergySurplus: { min: 0, max: 20, step: 0.05 },
  minSignalStrength: { min: 0, max: 1, step: 0.01 },
  pendingDensityDivisor: { min: 1, max: 1000, step: 1, integer: true },
  metabolism: { min: 0, max: 5, step: 0.001 },
  rewardScale: { min: 0, max: 50, step: 0.1 },
  lossHealthScale: { min: 0, max: 50, step: 0.1 },
  healthGainScale: { min: 0, max: 20, step: 0.1 },
  recentResolvedPayoffWindow: { min: 1, max: 500, step: 1, integer: true },
  agentRecentPayoffWindow: { min: 1, max: 200, step: 1, integer: true },
  reproductionEnergy: { min: 0, max: 200, step: 0.5 },
  reproductionCost: { min: 0, max: 100, step: 0.5 },
  reproductionMinResolved: { min: 0, max: 100, step: 1, integer: true },
  reproductionMinAveragePayoff: { min: -5, max: 5, step: 0.001 },
  deathEnergy: { min: -100, max: 100, step: 0.5 },
  deathHealth: { min: -50, max: 100, step: 1 },
  transactionCost: { min: 0, max: 2, step: 0.001 },
  initialHiddenUnitsMin: { min: 1, max: 256, step: 1, integer: true },
  initialHiddenUnitsMax: { min: 1, max: 512, step: 1, integer: true },
  initialInputConnectionsPerUnit: { min: 0, max: 64, step: 1, integer: true },
  initialRecurrentConnectionsPerUnit: { min: 0, max: 64, step: 1, integer: true },
  initialOutputConnectionsPerOutput: { min: 0, max: 128, step: 1, integer: true },
  newUnitInitialConnections: { min: 0, max: 128, step: 1, integer: true },
  newUnitExistingLayerChance: { min: 0, max: 1, step: 0.001 },
  newUnitNewLayerChance: { min: 0, max: 1, step: 0.001 },
  addUnitRate: { min: 0, max: 1, step: 0.001 },
  disableUnitRate: { min: 0, max: 1, step: 0.001 },
  reenableUnitRate: { min: 0, max: 1, step: 0.001 },
  addConnectionRate: { min: 0, max: 1, step: 0.001 },
  disableConnectionRate: { min: 0, max: 1, step: 0.001 },
  reenableConnectionRate: { min: 0, max: 1, step: 0.001 },
  allowSkipConnections: { min: 0, max: 1, step: 1, integer: true },
  allowInputToOutputConnections: { min: 0, max: 1, step: 1, integer: true },
  weightMutationRate: { min: 0, max: 1, step: 0.001 },
  weightMutationStdDev: { min: 0, max: 2, step: 0.001 },
  weightReplaceRate: { min: 0, max: 1, step: 0.001 },
  newConnectionWeightStdDev: { min: 0, max: 2, step: 0.001 },
  biasMutationRate: { min: 0, max: 1, step: 0.001 },
  biasMutationStdDev: { min: 0, max: 2, step: 0.001 },
  gateBiasStdDev: { min: 0, max: 2, step: 0.01 },
  outputBiasStdDev: { min: 0, max: 2, step: 0.01 },
  brainEnergyCostPerActiveUnit: { min: 0, max: 1, step: 0.0001 },
  brainEnergyCostPerActiveConnection: { min: 0, max: 1, step: 0.0001 },
  brainEnergyCostPerActiveLayer: { min: 0, max: 1, step: 0.0001 },
  cooldownOutputMultiplier: { min: 0, max: 10, step: 0.05 },
  baseMutationStdDev: { min: 0, max: 1, step: 0.001 },
  mutationStdDevMutationStdDev: { min: 0, max: 1, step: 0.001 },
  mutationStdDevMin: { min: 0, max: 1, step: 0.001 },
  mutationStdDevMax: { min: 0, max: 2, step: 0.001 },
  thresholdBiasInitialStdDev: { min: 0, max: 1, step: 0.001 },
  thresholdBiasMutationStdDev: { min: 0, max: 1, step: 0.001 },
  thresholdBiasMin: { min: -2, max: 2, step: 0.01 },
  thresholdBiasMax: { min: -2, max: 2, step: 0.01 },
  initialMinHorizonMin: { min: 0, max: 20, step: 0.05 },
  initialMinHorizonMax: { min: 0, max: 20, step: 0.05 },
  initialMaxHorizonMin: { min: 0, max: 30, step: 0.05 },
  initialMaxHorizonMax: { min: 0, max: 30, step: 0.05 },
  minHorizonMutationStdDev: { min: 0, max: 5, step: 0.01 },
  maxHorizonMutationStdDev: { min: 0, max: 5, step: 0.01 },
  minHorizonClampMin: { min: 0, max: 20, step: 0.05 },
  minHorizonClampMax: { min: 0, max: 20, step: 0.05 },
  maxHorizonClampMin: { min: 0, max: 30, step: 0.05 },
  maxHorizonClampMax: { min: 0, max: 30, step: 0.05 },
  cooldownBaseInitialMin: { min: 0, max: 20, step: 0.05 },
  cooldownBaseInitialMax: { min: 0, max: 20, step: 0.05 },
  cooldownBaseMutationStdDev: { min: 0, max: 5, step: 0.01 },
  cooldownBaseClampMin: { min: 0, max: 20, step: 0.05 },
  cooldownBaseClampMax: { min: 0, max: 20, step: 0.05 },
};

export function clampSpawnerValue(value: number, fallback: number, bounds: SpawnerConfigBounds) {
  const finiteValue = Number.isFinite(value) ? value : fallback;
  const rounded = bounds.integer ? Math.round(finiteValue) : finiteValue;
  return Math.min(bounds.max, Math.max(bounds.min, rounded));
}
