import type { SpawnerConfig } from "./spawnerSimulation";
import { clampNumber, finiteOr } from "./numeric";

export type SpawnerConfigBounds = {
  min: number;
  max: number;
  step: number;
  integer?: boolean;
};

export const SPAWNER_CONFIG_BOUNDS: Record<keyof SpawnerConfig, SpawnerConfigBounds> = {
  initialSpawners: { min: 1, max: 500, step: 1, integer: true },
  maxSpawners: { min: 1, max: 1000, step: 1, integer: true },
  foodHistoryTicks: { min: 1, max: 5000, step: 1, integer: true },
  initialEnergyMin: { min: 0, max: 200, step: 0.5 },
  initialEnergyMax: { min: 0, max: 250, step: 0.5 },
  initialHealth: { min: 1, max: 300, step: 1 },
  initialCooldownMaxTicks: { min: 0, max: 500, step: 1, integer: true },
  defaultSpawnThreshold: { min: 0, max: 1.5, step: 0.01 },
  spawnCost: { min: 0, max: 20, step: 0.05 },
  minimumSpawnEnergySurplus: { min: 0, max: 20, step: 0.05 },
  defaultMinSignalStrength: { min: 0, max: 1, step: 0.01 },
  defaultDeltaLag1FromTicks: { min: 0, max: 1000, step: 1, integer: true },
  defaultDeltaLag1ToTicks: { min: 0, max: 1000, step: 1, integer: true },
  defaultDeltaLag2FromTicks: { min: 0, max: 1000, step: 1, integer: true },
  defaultDeltaLag2ToTicks: { min: 0, max: 1000, step: 1, integer: true },
  defaultDeltaLag3FromTicks: { min: 0, max: 1000, step: 1, integer: true },
  defaultDeltaLag3ToTicks: { min: 0, max: 1000, step: 1, integer: true },
  defaultDeltaLag4FromTicks: { min: 0, max: 1000, step: 1, integer: true },
  defaultDeltaLag4ToTicks: { min: 0, max: 1000, step: 1, integer: true },
  defaultDeltaLag5FromTicks: { min: 0, max: 1000, step: 1, integer: true },
  defaultDeltaLag5ToTicks: { min: 0, max: 1000, step: 1, integer: true },
  defaultRollingWindowTicks: { min: 0, max: 1000, step: 1, integer: true },
  defaultLocalScaleWindowTicks: { min: 0, max: 1000, step: 1, integer: true },
  defaultLocalScaleSampleStepTicks: { min: 1, max: 1000, step: 1, integer: true },
  defaultVolumeScaleWindowTicks: { min: 0, max: 1000, step: 1, integer: true },
  defaultVolumeScaleSampleStepTicks: { min: 1, max: 1000, step: 1, integer: true },
  defaultVolumeDeltaLagTicks: { min: 0, max: 1000, step: 1, integer: true },
  defaultVolumeAccelerationLagTicks: { min: 0, max: 1000, step: 1, integer: true },
  defaultRsiWindowTicks: { min: 1, max: 1000, step: 1, integer: true },
  defaultVolumePriceAgreementLagTicks: { min: 0, max: 1000, step: 1, integer: true },
  defaultPayoffScaleWindowTicks: { min: 0, max: 1000, step: 1, integer: true },
  defaultPayoffScaleSampleStepTicks: { min: 1, max: 1000, step: 1, integer: true },
  defaultTrendWindowTicks: { min: 0, max: 1000, step: 1, integer: true },
  defaultCycleWindowTicks: { min: 0, max: 1000, step: 1, integer: true },
  defaultRoughnessSensitivity: { min: 0, max: 1, step: 0.001 },
  defaultPendingDensityScale: { min: 1, max: 1000, step: 1, integer: true },
  founderPerceptionRandomizationTicks: { min: 0, max: 1000, step: 1, integer: true },
  perceptionMutationRate: { min: 0, max: 1, step: 0.001 },
  perceptionLagMutationStdDev: { min: 0, max: 1000, step: 0.1 },
  perceptionWindowMutationStdDev: { min: 0, max: 1000, step: 0.1 },
  perceptionSensitivityMutationStdDev: { min: 0, max: 1, step: 0.0001 },
  perceptionDensityScaleMutationStdDev: { min: 0, max: 1000, step: 0.1 },
  payoffScaleMutationRate: { min: 0, max: 1, step: 0.001 },
  payoffScaleWindowMutationStdDev: { min: 0, max: 1000, step: 0.1 },
  payoffScaleSampleStepMutationStdDev: { min: 0, max: 1000, step: 0.1 },
  tradingPolicyMutationRate: { min: 0, max: 1, step: 0.001 },
  spawnThresholdMutationStdDev: { min: 0, max: 1, step: 0.001 },
  minSignalStrengthMutationStdDev: { min: 0, max: 1, step: 0.001 },
  mutationProfileMutationStdDev: { min: 0, max: 1, step: 0.001 },
  energyDrainPerTick: { min: 0, max: 5, step: 0.001 },
  rewardScale: { min: 0, max: 50, step: 0.1 },
  lossHealthScale: { min: 0, max: 50, step: 0.1 },
  healthGainScale: { min: 0, max: 20, step: 0.1 },
  recentResolvedPayoffWindow: { min: 1, max: 500, step: 1, integer: true },
  agentRecentPayoffWindow: { min: 1, max: 200, step: 1, integer: true },
  uniquenessPopulationLimit: { min: 1, max: 1000, step: 1, integer: true },
  plasticityWeightLearningRate: { min: 0, max: 1, step: 0.001 },
  plasticityBiasLearningRate: { min: 0, max: 1, step: 0.001 },
  plasticityPositiveRewardMultiplier: { min: 0, max: 10, step: 0.01 },
  plasticityNegativeRewardMultiplier: { min: 0, max: 10, step: 0.01 },
  plasticityReproductionRewardStrength: { min: 0, max: 1, step: 0.01 },
  plasticityExperienceDecayRate: { min: 0, max: 1, step: 0.001 },
  plasticityMaxLearnedDelta: { min: 0.001, max: 100, step: 0.01 },
  plasticityEligibilityTraceStrength: { min: 0, max: 1, step: 0.001 },
  plasticityMutationStdDev: { min: 0, max: 1, step: 0.001 },
  reproductionEnergy: { min: 0, max: 200, step: 0.5 },
  reproductionCost: { min: 0, max: 100, step: 0.5 },
  reproductionCostMinMultiplier: { min: 0, max: 10, step: 0.01 },
  reproductionCostMaxMultiplier: { min: 0, max: 20, step: 0.01 },
  reproductionCostPressureCurve: { min: 0, max: 10, step: 0.01 },
  initialReproductionOutputBias: { min: -12, max: 2, step: 0.1 },
  deathEnergy: { min: -100, max: 100, step: 0.5 },
  deathHealth: { min: -50, max: 100, step: 1 },
  transactionCost: { min: 0, max: 2, step: 0.001 },
  initialHiddenUnitsMin: { min: 1, max: 256, step: 1, integer: true },
  initialHiddenUnitsMax: { min: 1, max: 512, step: 1, integer: true },
  initialInputConnectionsPerUnit: { min: 0, max: 64, step: 1, integer: true },
  initialRecurrentConnectionsPerUnit: { min: 0, max: 64, step: 1, integer: true },
  initialOutputConnectionsPerOutput: { min: 0, max: 128, step: 1, integer: true },
  newUnitInitialConnections: { min: 2, max: 128, step: 1, integer: true },
  newUnitExistingLayerChance: { min: 0, max: 1, step: 0.001 },
  newUnitNewLayerChance: { min: 0, max: 1, step: 0.001 },
  addUnitRate: { min: 0, max: 1, step: 0.001 },
  disableUnitRate: { min: 0, max: 1, step: 0.001 },
  reenableUnitRate: { min: 0, max: 1, step: 0.001 },
  addConnectionRate: { min: 0, max: 1, step: 0.001 },
  disableConnectionRate: { min: 0, max: 1, step: 0.001 },
  reenableConnectionRate: { min: 0, max: 1, step: 0.001 },
  allowSkipConnections: { min: 0, max: 1, step: 1, integer: true },
  allowInputToOutputConnections: { min: 0, max: 1, step: 1, integer: true },
  weightMutationRate: { min: 0, max: 1, step: 0.001 },
  weightMutationStdDev: { min: 0, max: 2, step: 0.001 },
  weightReplaceRate: { min: 0, max: 1, step: 0.001 },
  newConnectionWeightStdDev: { min: 0, max: 2, step: 0.001 },
  biasMutationRate: { min: 0, max: 1, step: 0.001 },
  biasMutationStdDev: { min: 0, max: 2, step: 0.001 },
  gateBiasStdDev: { min: 0, max: 2, step: 0.01 },
  outputBiasStdDev: { min: 0, max: 2, step: 0.01 },
  brainEnergyCostPerActiveUnit: { min: 0, max: 1, step: 0.0001 },
  brainEnergyCostPerActiveConnection: { min: 0, max: 1, step: 0.0001 },
  brainEnergyCostPerActiveLayer: { min: 0, max: 1, step: 0.0001 },
  cooldownOutputMultiplierTicks: { min: 0, max: 500, step: 1, integer: true },
  thresholdBiasInitialStdDev: { min: 0, max: 1, step: 0.001 },
  thresholdBiasMutationStdDev: { min: 0, max: 1, step: 0.001 },
  thresholdBiasMin: { min: -2, max: 2, step: 0.01 },
  thresholdBiasMax: { min: -2, max: 2, step: 0.01 },
  initialMinHorizonTicksMin: { min: 1, max: 1000, step: 1, integer: true },
  initialMinHorizonTicksMax: { min: 1, max: 1000, step: 1, integer: true },
  initialMaxHorizonTicksMin: { min: 1, max: 1500, step: 1, integer: true },
  initialMaxHorizonTicksMax: { min: 1, max: 1500, step: 1, integer: true },
  minHorizonTicksMutationStdDev: { min: 0, max: 250, step: 0.1 },
  maxHorizonTicksMutationStdDev: { min: 0, max: 250, step: 0.1 },
  minHorizonTicksClampMin: { min: 1, max: 1000, step: 1, integer: true },
  minHorizonTicksClampMax: { min: 1, max: 1000, step: 1, integer: true },
  maxHorizonTicksClampMin: { min: 1, max: 1500, step: 1, integer: true },
  maxHorizonTicksClampMax: { min: 1, max: 1500, step: 1, integer: true },
  cooldownBaseTicksInitialMin: { min: 0, max: 500, step: 1, integer: true },
  cooldownBaseTicksInitialMax: { min: 0, max: 500, step: 1, integer: true },
  cooldownBaseTicksMutationStdDev: { min: 0, max: 250, step: 0.1 },
  cooldownBaseTicksClampMin: { min: 0, max: 500, step: 1, integer: true },
  cooldownBaseTicksClampMax: { min: 0, max: 500, step: 1, integer: true },
};

export function clampSpawnerValue(value: number | undefined, fallback: number, bounds: SpawnerConfigBounds) {
  const finiteValue = finiteOr(value, fallback);
  const rounded = bounds.integer ? Math.round(finiteValue) : finiteValue;
  return clampNumber(rounded, bounds.min, bounds.max);
}
