import { runSuite } from "./sine-tests/helpers";
import { tests as genomeTests } from "./sine-tests/genome.test";
import { tests as genomeMutationTests } from "./sine-tests/genomeMutation.test";
import { tests as genomeRuntimeTests } from "./sine-tests/genomeRuntime.test";
import { tests as inputMetadataTests } from "./sine-tests/inputMetadata.test";
import { tests as settingsTests } from "./sine-tests/settings.test";
import { tests as marketDataTests } from "./sine-tests/marketData.test";
import { tests as marketInputsTests } from "./sine-tests/marketInputs.test";
import { tests as spawnerWorldTests } from "./sine-tests/spawnerWorld.test";
import { tests as timelineTests } from "./sine-tests/timeline.test";
import { tests as uniquenessTests } from "./sine-tests/uniqueness.test";
import { tests as uniquenessTelemetryTests } from "./sine-tests/uniquenessTelemetry.test";
import { tests as workerProtocolTests } from "./sine-tests/workerProtocol.test";
import { tests as sinePersistenceTests } from "./sine-tests/sinePersistence.test";
import { tests as persistencePacketTests } from "./sine-tests/persistencePacket.test";
import { tests as persistenceOutboxTests } from "./sine-tests/persistenceOutbox.test";
import { tests as perceptionMutationProfileTests } from "./sine-tests/perceptionMutationProfile.test";

runSuite("timeline", timelineTests);
runSuite("spawner world", spawnerWorldTests);
runSuite("settings", settingsTests);
runSuite("input metadata", inputMetadataTests);
runSuite("market data", marketDataTests);
runSuite("market inputs", marketInputsTests);
runSuite("perception and mutation profile", perceptionMutationProfileTests);
runSuite("genome", genomeTests);
runSuite("genome mutation", genomeMutationTests);
runSuite("genome runtime", genomeRuntimeTests);
runSuite("uniqueness", uniquenessTests);
runSuite("uniqueness telemetry", uniquenessTelemetryTests);
runSuite("worker protocol", workerProtocolTests);
runSuite("persistence packet", persistencePacketTests);
runSuite("persistence outbox", persistenceOutboxTests);
runSuite("sine persistence", sinePersistenceTests);

console.log("Sine simulator contract tests passed.");
