import { runSuite } from "./sine-tests/helpers";
import { tests as genomeTests } from "./sine-tests/genome.test";
import { tests as genomeMutationTests } from "./sine-tests/genomeMutation.test";
import { tests as genomeRuntimeTests } from "./sine-tests/genomeRuntime.test";
import { tests as inputMetadataTests } from "./sine-tests/inputMetadata.test";
import { tests as settingsTests } from "./sine-tests/settings.test";
import { tests as marketDataTests } from "./sine-tests/marketData.test";
import { tests as marketInputsTests } from "./sine-tests/marketInputs.test";
import { tests as spawnerWorldTests } from "./sine-tests/spawnerWorld.test";
import { tests as spawnerWorldFoodTests } from "./sine-tests/spawnerWorldFood.test";
import { tests as spawnerWorldLearningTests } from "./sine-tests/spawnerWorldLearning.test";
import { tests as spawnerWorldLifecycleTests } from "./sine-tests/spawnerWorldLifecycle.test";
import { tests as spawnerWorldReproductionTests } from "./sine-tests/spawnerWorldReproduction.test";
import { tests as spawnerWorldTelemetryTests } from "./sine-tests/spawnerWorldTelemetry.test";
import { tests as timelineTests } from "./sine-tests/timeline.test";
import { tests as uniquenessTests } from "./sine-tests/uniqueness.test";
import { tests as uniquenessTelemetryTests } from "./sine-tests/uniquenessTelemetry.test";
import { tests as strategyMapTests } from "./sine-tests/strategyMap.test";
import { tests as selectedSpawnerTimelineTests } from "./sine-tests/selectedSpawnerTimeline.test";
import { tests as selectedSpawnerPanelModelTests } from "./sine-tests/selectedSpawnerPanelModel.test";
import { tests as chartMathTests } from "./sine-tests/chartMath.test";
import { tests as workerProtocolTests } from "./sine-tests/workerProtocol.test";
import { tests as sinePersistenceBasicTests } from "./sine-tests/sinePersistenceBasic.test";
import { tests as sinePersistenceDiagnosticsTests } from "./sine-tests/sinePersistenceDiagnostics.test";
import { tests as sinePersistenceCohortTests } from "./sine-tests/sinePersistenceCohort.test";
import { tests as sinePersistenceInspectionTests } from "./sine-tests/sinePersistenceInspection.test";
import { tests as sinePersistenceHeadlessSchemaTests } from "./sine-tests/sinePersistenceHeadlessSchema.test";
import { tests as persistencePacketTests } from "./sine-tests/persistencePacket.test";
import { tests as persistenceOutboxTests } from "./sine-tests/persistenceOutbox.test";
import { tests as perceptionMutationProfileTests } from "./sine-tests/perceptionMutationProfile.test";
import { tests as parityFixtureTests } from "./sine-tests/parityFixtures.test";
import { tests as exactParityTests } from "./sine-tests/exactParity.test";
import { tests as brainEvaluationTests } from "./sine-tests/brainEvaluation.test";
import { tests as workerUiTests } from "./sine-tests/workerUi.test";
import { tests as plasticityTests } from "./sine-tests/plasticity.test";
import { tests as plasticityComparisonTests } from "./sine-tests/plasticityComparison.test";
import { tests as sineApiTests } from "./sine-tests/sineApi.test";
import { tests as sineRoutesTests } from "./sine-tests/sineRoutes.test";
import { tests as headlessTests } from "./sine-tests/headless.test";
import { tests as runDiagnosticsTests } from "./sine-tests/runDiagnostics.test";

await runSuite("timeline", timelineTests);
await runSuite("parity fixtures", parityFixtureTests);
await runSuite("exact parity", exactParityTests);
await runSuite("brain evaluation", brainEvaluationTests);
await runSuite("spawner world", spawnerWorldTests);
await runSuite("spawner world food", spawnerWorldFoodTests);
await runSuite("spawner world learning", spawnerWorldLearningTests);
await runSuite("spawner world lifecycle", spawnerWorldLifecycleTests);
await runSuite("spawner world reproduction", spawnerWorldReproductionTests);
await runSuite("spawner world telemetry", spawnerWorldTelemetryTests);
await runSuite("settings", settingsTests);
await runSuite("input metadata", inputMetadataTests);
await runSuite("market data", marketDataTests);
await runSuite("market inputs", marketInputsTests);
await runSuite("perception and mutation profile", perceptionMutationProfileTests);
await runSuite("plasticity", plasticityTests);
await runSuite("plasticity comparison", plasticityComparisonTests);
await runSuite("genome", genomeTests);
await runSuite("genome mutation", genomeMutationTests);
await runSuite("genome runtime", genomeRuntimeTests);
await runSuite("uniqueness", uniquenessTests);
await runSuite("uniqueness telemetry", uniquenessTelemetryTests);
await runSuite("strategy map", strategyMapTests);
await runSuite("selected spawner timeline", selectedSpawnerTimelineTests);
await runSuite("selected spawner panel model", selectedSpawnerPanelModelTests);
await runSuite("chart math", chartMathTests);
await runSuite("worker protocol", workerProtocolTests);
await runSuite("worker ui", workerUiTests);
await runSuite("sine api", sineApiTests);
await runSuite("sine routes", sineRoutesTests);
await runSuite("run diagnostics", runDiagnosticsTests);
await runSuite("headless", headlessTests);
await runSuite("persistence packet", persistencePacketTests);
await runSuite("persistence outbox", persistenceOutboxTests);
await runSuite("sine persistence basic", sinePersistenceBasicTests);
await runSuite("sine persistence diagnostics", sinePersistenceDiagnosticsTests);
await runSuite("sine persistence cohort", sinePersistenceCohortTests);
await runSuite("sine persistence inspection", sinePersistenceInspectionTests);
await runSuite("sine persistence headless schema", sinePersistenceHeadlessSchemaTests);

console.log("Sine simulator contract tests passed.");
