import type { Lesson } from "./types";

export const LESSONS: Lesson[] = [
  {
    id: "node",
    title: "One Node",
    model: "nn",
    scenario: "react-now",
    summary: "A node is a tiny calculator: multiply the input, add bias, squash the result, send it forward.",
    plain: "A neural network starts with simple pieces. One node turns an input number into an output number.",
    watch: ["Blue carries the current input.", "The weight can flip or amplify the input.", "The squashing function keeps output between -1 and 1."],
    controls: ["inputWeight", "bias"],
  },
  {
    id: "feedforward",
    title: "Feed-Forward Network",
    model: "nn",
    scenario: "react-now",
    summary: "A feed-forward network chains nodes into layers. Information moves left to right only.",
    plain: "Hidden nodes are intermediate calculations. They do not remember anything unless you add a memory loop.",
    watch: ["Input nodes feed hidden nodes.", "Hidden nodes feed output nodes.", "No arrow loops back to the next tick."],
    controls: ["inputWeight", "bias"],
  },
  {
    id: "time",
    title: "Time And Memory",
    model: "rnn",
    scenario: "remember-pulse",
    summary: "A tick is one moment in a sequence. Memory is a value carried from the previous tick.",
    plain: "The same network runs again and again. A memory model carries one value forward so the next tick can use it.",
    watch: ["Press Step and the tick advances.", "Green carries previous memory.", "The timeline records what survives over time."],
    controls: ["startingMemory"],
  },
  {
    id: "rnn",
    title: "Vanilla RNN",
    model: "rnn",
    scenario: "remember-pulse",
    summary: "A vanilla RNN mixes current input with previous hidden memory, then overwrites memory.",
    plain: "The RNN remembers by feeding yesterday's hidden value into today's calculation.",
    watch: ["Input disappears after the pulse.", "Output can stay positive because memory loops back.", "Memory weight controls how strongly the past matters."],
    controls: ["inputWeight", "memoryWeight", "startingMemory"],
  },
  {
    id: "gru",
    title: "GRU",
    model: "gru",
    scenario: "forget-noise",
    summary: "A GRU adds reset and update gates so memory can be kept, ignored, or overwritten.",
    plain: "A GRU is a controlled-memory RNN. Its gates are like valves.",
    watch: ["Reset controls whether old memory helps create the candidate.", "Update controls how much old memory is replaced.", "A low update gate preserves memory."],
    controls: ["inputWeight", "memoryWeight", "startingMemory", "resetGate", "updateGate"],
  },
  {
    id: "lstm",
    title: "LSTM",
    model: "lstm",
    scenario: "flip-direction",
    summary: "An LSTM separates private cell memory from visible hidden output.",
    plain: "Think of the cell as a notebook. Forget erases, write adds new notes, output decides what is visible.",
    watch: ["Red is cell state.", "Forget controls old cell memory.", "Output gate can hide memory even when the cell still holds it."],
    controls: ["inputWeight", "memoryWeight", "startingMemory", "forgetGate", "writeGate", "outputGate"],
  },
  {
    id: "sine",
    title: "Sine-Style Sparse GRU",
    model: "sine-gru",
    scenario: "sine-agent",
    summary: "Sine agents use sparse GRU-like hidden units rather than neat dense textbook layers.",
    plain: "A Sine brain is an evolved graph. Some inputs connect to some gates, previous hidden values feed the next tick, and current hidden values feed outputs.",
    watch: ["Dashed green means previous tick memory, not a same-tick loop.", "Amber paths feed update/reset/candidate gates.", "Purple paths are hidden-to-output action links."],
    controls: ["inputWeight", "memoryWeight", "startingMemory", "resetGate", "updateGate"],
  },
];
